# Based on pnpm.io/docker
# Primary Stage: Node Image with PNPM
FROM node:18-alpine3.17 as primary
RUN apk --no-cache add curl
RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm


# Secondary Stage: Development
FROM primary as secondary
ARG APP 
ARG NODE_ENV=development 
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app
COPY package.json pnpm-lock.yaml ./

RUN pnpm --filter ${APP} deploy --dev secondary


## Tertiary Stage: Pruned
FROM node:18-alpine3.17
WORKDIR /app
ENV NODE_ENV=development

COPY --from=secondary /usr/src/app/pruned/node_modules node_modules

LABEL version="1.0"
LABEL description="Image: FEM MONOREPO DEV"
EXPOSE 4000