# Based on pnpm.io/docker
# Primary Stage: Node Image with PNPM
FROM node:18-alpine3.17 as primary
RUN apk --no-cache add curl
RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# Secondary Stage: MonoRepo Base
FROM primary as secondary
COPY . /monorepo
WORKDIR /monorepo
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile --offline
RUN pnpm --filter=@apps/kanban-task-app-api deploy --dev /devapp


# # Tertiary Stage: Specific App Deployment
FROM primary as tertiary
COPY --from=secondary /devapp /app
WORKDIR /app

LABEL version="1.0"
LABEL description="Image: FEM MONOREPO DEV"
EXPOSE 4000