# Based on pnpm.io/docker
# Primary Stage: Node Image with PNPM
FROM node:18-alpine3.17 as primary
WORKDIR /app

RUN apk --no-cache add curl
RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

COPY pnpm-lock.yaml ./

RUN pnpm fetch --dev
ADD . ./
RUN pnpm install -r --offline --dev

# Secondary Stage: Development
FROM primary as secondary
WORKDIR /app

ARG service
RUN pnpm --filter ${service} deploy --dev secondary

## Tertiary Stage: Pruned
FROM node:18-alpine3.17
WORKDIR /app
ENV NODE_ENV=development

COPY --from=secondary /app/secondary/node_modules node_modules

LABEL version="1.0"
LABEL description="Image: FEM MONOREPO DEV"
EXPOSE 4000