# Based on pnpm.io/docker
# Primary Stage: Node Image with PNPM
FROM node:18-alpine3.17 as primary
RUN apk --no-cache add curl
RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"


# # Secondary Stage: MonoRepo Dependencies
# FROM primary as secondary
# WORKDIR /app

# COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
# RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile


# # Tertiary Stage: Specific App Deployment
# FROM secondary as tertiary
# ARG APP
# WORKDIR /app
# RUN pnpm deploy --filter ${APP} --dev /dev/app

# # Secondary Stage: MonoRepo Dependencies
FROM primary as secondary
WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --offline --frozen-lockfile
ARG APP
RUN pnpm deploy --filter @apps/kanban-task-app-api --dev /dev/app


# Quaternary Stage: Final Development Image
# FROM secondary as tertiary
# COPY --from=secondary /dev/app /app
# # FROM tertiary as quaternary
# # COPY --from=tertiary /dev/app /app
# WORKDIR /app

# LABEL version="1.0"
# LABEL description="Image: FEM MONOREPO DEV"
# EXPOSE 4000