packages:
  - 'apps/**'
  - 'packages/**'

allowBuilds:
  '@swc/core': true
  core-js: true
  core-js-pure: true
  cwebp-bin: set this to true or false
  esbuild: true
  gifsicle: set this to true or false
  iltorb: set this to true or false
  mozjpeg: set this to true or false
  pngquant-bin: set this to true or false
  secp256k1: true

minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - '@types/*'
  - '@secretlint/*'
  - 'secretlint'
