packages:
  - 'apps/**'
  - 'packages/**'

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  core-js-pure: true
  cwebp-bin: true
  esbuild: true
  gifsicle: true
  iltorb: true
  mozjpeg: true
  pngquant-bin: true
  secp256k1: true
  unrs-resolver: true

minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - '@types/*'
  - '@secretlint/*'
  - 'secretlint'

overrides:
  unrs-resolver: '1.11.1'
