# // NOTE:  Not to be used - still trying to ascertain uid/gid best practices.
# Primary Stage
FROM node:18-alpine3.17
LABEL version="1.0"
LABEL description="Image: #35 Kanban: API: Node Express"

WORKDIR /app/backend
COPY ./package.json .
USER root
RUN addgroup -S devApp && adduser -S devApp -G devApp
USER devApp
EXPOSE 4000

